# We use Cirrus CI to test on FreeBSD.
# For GNU/Linux CI see GitHub Actions.

freebsd_instance:
  image_family: freebsd-13-1

main_freebsd_task:
  name: Main (FreeBSD)
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_BASE_BRANCH == 'master'
  dependencies_script:
    - pkg install --yes autoconf automake cppcheck libtool libyaml py39-pip py39-wheel python3
    - pip install --user Jinja2 PyYAML
  main_build_script:
    - ./autogen.sh
    - ./configure --enable-checks-all CFLAGS='-O3'
    - make
    - sudo make install
  main_test_script:
    - make check
